### ISSUE TITLE
Are we in the right way?

### ISSUE THREAD

**Issue by deniz777** [PatrickLouys/professional-php-sample-code#6]
Hello, I do not develop web applications so often. I did not want to use popular frameworks like laravel, because I did not want to learn all changes everytime when I start to write new app. That's why I bought this book and wanted to create my own little framework with modern way. But after I see some bad codes in SubmisionController, I am not sure anymore that I am following the right guy. So I want to ask some questions about our structure:
1) Why did we create two Submission classes? One is in "src\FrontPage\Application\", the other one is in "src\Submission\Domain\" They are doing similar jobs. Isn't it against DRY? We did similar things for "Users" too, not asking only for Submissions.
2) We created "CurrentUserFactory.php" interface never used it in "SymfonySessionCurrentUserFactory.php". Why we are creating it?
3) We used "AuthenticatedUser" class in "SubmissionForm.php" but when using one method of "SubmissionForm", we sent "User" as a parameter. Maybe we need to use "User" class in "SubmissionForm.php" ?

**Comment by PatrickLouys** [comment]
1. No this is not a DRY violation, they represent different things. The application follows CQRS and one is on the write side of things, the other one on the read side. One is a domain entity, the other is just a simple PHP object to give some structure to the query data.

2. Good catch, this is a mistake. The interface exists because we are going across a boundary and to make it easy to switch out the implementation later. But I forgot the implements and since it is only ever used directly in the dependencies file, it went unnoticed. But you were to use the factory from other code, you would use the interface.

3. This should be correct. The code makes sure that an AuthenticatedUser is sent. See https://github.com/PatrickLouys/professional-php-sample-code/blob/master/src/Submission/Presentation/SubmissionController.php#L70-L72

Hope that helps :)

**Comment by deniz777** [comment]
I rechecked the codes for question 1 and 3, now I understood you better. Still I need to research more for CQRS, because I did not like this approach in this example.

Anyway, I will follow the book, thanks for your helps.
